# Generated by Django 5.2.2 on 2025-07-09 21:00

import fur_pdf_editor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fur_pdf_editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('notsay', 'Prefer not to say')], default='notsay', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=fur_pdf_editor.models.user_profile_pic_path),
        ),
    ]
